## Blood mask prep

Okay, let's just binarize these blood masks.

In [26]:
import os

# Define the directory containing the files
directory = '/Users/jamesemilian/triage/hemobox/data/2614704/Triage-Labeling/hand_held_camera/frames/19/images'

# Loop through all the files in the directory
for filename in os.listdir(directory):
    # Get the full path to the current file
    old_file = os.path.join(directory, filename)

    # Only rename files (skip directories)
    if os.path.isfile(old_file):
        # Define the new filename with 'adt1_' prefixed
        new_filename = 'hh19_' + filename
        new_file = os.path.join(directory, new_filename)

        # Rename the file
        os.rename(old_file, new_file)

print("Files renamed successfully!")

Files renamed successfully!


Now, organize into a single rgb_masks folder - apply binarize -> and save in a new blood_gray folder.

In [28]:
import os
import shutil

# Define your main folder and destination folders
main_folder = '/Users/jamesemilian/triage/hemobox/data/2614704/Triage-Labeling'
destination_images_folder = '/Users/jamesemilian/triage/hemobox/data/f8-data/images'
destination_masks_folder = '/Users/jamesemilian/triage/hemobox/data/f8-data/masks'

# Create destination directories if they don't exist
os.makedirs(destination_images_folder, exist_ok=True)
os.makedirs(destination_masks_folder, exist_ok=True)

def copy_files_from_subfolders(main_folder, folder_name, destination_folder):
    # Walk through the directory structure
    for root, dirs, files in os.walk(main_folder):
        if os.path.basename(root) == folder_name:
            # Copy all files from the current 'images' or 'masks' folder to the corresponding destination
            for file in files:
                source_file = os.path.join(root, file)
                destination_file = os.path.join(destination_folder, file)
                shutil.copy(source_file, destination_file)
                print(f"Copied {source_file} to {destination_file}")

# Copy files from 'images' subfolders
copy_files_from_subfolders(main_folder, 'images', destination_images_folder)

# Copy files from 'masks' subfolders
copy_files_from_subfolders(main_folder, 'masks', destination_masks_folder)

print("All files copied successfully!")

Copied /Users/jamesemilian/triage/hemobox/data/2614704/Triage-Labeling/airport_data_take3/attachment-1/rgb/rgb_frames/images/adt3_image_1261.jpeg to /Users/jamesemilian/triage/hemobox/data/f8-data/images/adt3_image_1261.jpeg
Copied /Users/jamesemilian/triage/hemobox/data/2614704/Triage-Labeling/airport_data_take3/attachment-1/rgb/rgb_frames/images/adt3_image_1.jpeg to /Users/jamesemilian/triage/hemobox/data/f8-data/images/adt3_image_1.jpeg
Copied /Users/jamesemilian/triage/hemobox/data/2614704/Triage-Labeling/airport_data_take3/attachment-1/rgb/rgb_frames/images/adt3_image_72.jpeg to /Users/jamesemilian/triage/hemobox/data/f8-data/images/adt3_image_72.jpeg
Copied /Users/jamesemilian/triage/hemobox/data/2614704/Triage-Labeling/airport_data_take3/attachment-1/rgb/rgb_frames/images/adt3_image_1053.jpeg to /Users/jamesemilian/triage/hemobox/data/f8-data/images/adt3_image_1053.jpeg
Copied /Users/jamesemilian/triage/hemobox/data/2614704/Triage-Labeling/airport_data_take3/attachment-1/rgb/rgb

In [1]:
!pip install pillow

In [2]:
from PIL import Image
import numpy as np

# Load the grayscale image (mask)
image_path = '/Users/jamesemilian/Downloads/03.png'
image = Image.open(image_path)

# Convert the image to a numpy array to inspect pixel values
image_array = np.array(image)

# Check the shape of the image (it should be 2D for grayscale)
print(f"Image shape: {image_array.shape}")

# Display some basic stats about pixel values
print(f"Minimum pixel value: {image_array.min()}")
print(f"Maximum pixel value: {image_array.max()}")

# Print the pixel values (this might be a lot for large images, so consider slicing)
print("Pixel values:")
print(image_array)

# You can also look at a small section of the image
print("Top-left 5x5 pixel values:")
print(image_array[:5, :5])

Image shape: (722, 758, 4)
Minimum pixel value: 0
Maximum pixel value: 255
Pixel values:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
Top-left 5x5 pixel values:
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [3]:
import numpy as np
np.array(1)

array(1)

In [6]:
from PIL import Image
import numpy as np

# Load the RGB image
image_path = '/Users/jamesemilian/triage/hemobox/data/f8-data/masks_rgb/adt2_image_104.png'
image = Image.open(image_path)

# Convert the image to a numpy array (HxWx3 for RGB)
image_array = np.array(image)

# Define the target colors in RGB
color_1 = np.array([0x3c, 0x17, 0xff])  # #3c17ff
color_2 = np.array([0xff, 0xc1, 0x17])  # #ffc117

# Create a binary mask
binary_mask = np.zeros(image_array.shape[:2], dtype=np.uint8)

# Only consider the first 3 channels (RGB) for comparison
rgb_image_array = image_array[:, :, :3]
# Find the pixels that match either color_1 or color_2
binary_mask[np.all(rgb_image_array == color_1, axis=-1)] = 255
binary_mask[np.all(rgb_image_array == color_2, axis=-1)] = 255

# Convert the mask to have 4 channels (HxWx4)
binary_mask_rgba = np.stack([binary_mask]*4, axis=-1)

# Convert back to an image
binary_mask_image = Image.fromarray(binary_mask_rgba)

# Save the binary mask image
binary_mask_image.save('/Users/jamesemilian/triage/hemobox/data/f8-data/masks_gray/binary_bloodmask2.png')

print("Binary mask created and saved successfully!")

Binary mask created and saved successfully!


In [7]:
import os
from PIL import Image
import numpy as np

# Define the source and destination folders
source_folder = '/Users/jamesemilian/triage/hemobox/data/f8-data/masks_rgb'
destination_folder = '/Users/jamesemilian/triage/hemobox/data/f8-data/masks_gray'

# Define the target colors in RGB
color_1 = np.array([0x3c, 0x17, 0xff])  # #3c17ff
color_2 = np.array([0xff, 0xc1, 0x17])  # #ffc117

# Ensure the destination folder exists
os.makedirs(destination_folder, exist_ok=True)

# Loop through all files in the source folder
for filename in os.listdir(source_folder):
    if filename.endswith(".png"):  # Only process .png files
        # Construct full file path
        image_path = os.path.join(source_folder, filename)
        
        # Load the RGB image
        image = Image.open(image_path)

        # Convert the image to a numpy array (HxWx3 for RGB)
        image_array = np.array(image)

        # Create a binary mask
        binary_mask = np.zeros(image_array.shape[:2], dtype=np.uint8)

        # Only consider the first 3 channels (RGB) for comparison
        rgb_image_array = image_array[:, :, :3]

        # Find the pixels that match either color_1 or color_2
        binary_mask[np.all(rgb_image_array == color_1, axis=-1)] = 255
        binary_mask[np.all(rgb_image_array == color_2, axis=-1)] = 255

        # Convert the mask to have 4 channels (HxWx4)
        binary_mask_rgba = np.stack([binary_mask] * 4, axis=-1)

        # Convert back to an image
        binary_mask_image = Image.fromarray(binary_mask_rgba)

        # Save the binary mask image in the destination folder
        save_path = os.path.join(destination_folder, filename)
        binary_mask_image.save(save_path)

        print(f"Binary mask for {filename} created and saved successfully!")

print("All images processed successfully!")

Binary mask for hh17_300.png created and saved successfully!
Binary mask for hh6_350.png created and saved successfully!
Binary mask for adt2_image_1142.png created and saved successfully!
Binary mask for hh8_500.png created and saved successfully!
Binary mask for hh16_2200.png created and saved successfully!
Binary mask for hh12_1850.png created and saved successfully!
Binary mask for adt2_image_1034.png created and saved successfully!
Binary mask for hh19_1500.png created and saved successfully!
Binary mask for hh8_700.png created and saved successfully!
Binary mask for adt4_image_315.png created and saved successfully!
Binary mask for adt4_image_1230.png created and saved successfully!
Binary mask for hh17_50.png created and saved successfully!
Binary mask for hh9_300.png created and saved successfully!
Binary mask for image_354.png created and saved successfully!
Binary mask for hh6_550.png created and saved successfully!
Binary mask for hh6_1600.png created and saved successfully!

Nov 15 - extracting data from F8.

In [1]:
import os
from PIL import Image
import numpy as np

# Define the source and destination folders
source_folder = '/Users/jamesemilian/triage/hemobox/data/f8-data-v2/2663250/masks_rgb'
destination_folder = '/Users/jamesemilian/triage/hemobox/data/f8-data-v2/2663250/masks_gray'

# Define the target colors in RGB
color_1 = np.array([0x3c, 0x17, 0xff])  # #3c17ff - blood_on_skin
color_2 = np.array([0xff, 0xc1, 0x17])  # #ffc117 - blood_on_ground
color_3 = np.array([0x35, 0xff, 0x1f])  # #35ff1f - blood_mask
color_4 = np.array([0xe3, 0x17, 0xff])  # #e317ff - pooled_blood


# Ensure the destination folder exists
os.makedirs(destination_folder, exist_ok=True)

# Loop through all files in the source folder
for filename in os.listdir(source_folder):
    if filename.endswith(".png"):  # Only process .png files
        # Construct full file path
        image_path = os.path.join(source_folder, filename)
        
        # Load the RGB image
        image = Image.open(image_path)

        # Convert the image to a numpy array (HxWx3 for RGB)
        image_array = np.array(image)

        # Create a binary mask
        binary_mask = np.zeros(image_array.shape[:2], dtype=np.uint8)

        # Only consider the first 3 channels (RGB) for comparison
        rgb_image_array = image_array[:, :, :3]

        # Find the pixels that match either color_1 or color_2
        binary_mask[np.all(rgb_image_array == color_1, axis=-1)] = 255
        binary_mask[np.all(rgb_image_array == color_2, axis=-1)] = 255
        binary_mask[np.all(rgb_image_array == color_3, axis=-1)] = 255
        binary_mask[np.all(rgb_image_array == color_4, axis=-1)] = 255

        # Convert the mask to have 4 channels (HxWx4)
        binary_mask_rgba = np.stack([binary_mask] * 4, axis=-1)

        # Convert back to an image
        binary_mask_image = Image.fromarray(binary_mask_rgba)

        # Save the binary mask image in the destination folder
        save_path = os.path.join(destination_folder, filename)
        binary_mask_image.save(save_path)

        print(f"Binary mask for {filename} created and saved successfully!")

print("All images processed successfully!")

Binary mask for 1727706822036658287.png created and saved successfully!
Binary mask for 1727706998961136341.png created and saved successfully!
Binary mask for iphone1_regular_view_arframe_image_compressed-1727622903-6757497.png created and saved successfully!
Binary mask for iphone1_regular_view_arframe_image_compressed-1727622896-239533185.png created and saved successfully!
Binary mask for image_20231129_141212.png created and saved successfully!
Binary mask for 1727638355045855045.png created and saved successfully!
Binary mask for 1727638359313021183.png created and saved successfully!
Binary mask for 1727707511321187019.png created and saved successfully!
Binary mask for 1727622966093585014.png created and saved successfully!
Binary mask for 1727623311595807075.png created and saved successfully!
Binary mask for iphone1_regular_view_arframe_image_compressed-1727623184-976306438.png created and saved successfully!
Binary mask for 1727637858893651723.png created and saved successfu

Alright - the masks were processed. Now what? Now - need to see which images were empty - and compy them because masks were not created for those.

In [5]:
pwd

'/Users/jamesemilian/triage/hemobox'

Need to org all my image into a single dir first:

In [ ]:
import os
import shutil

# Define the base directory and target directory
base_directory = '/Users/jamesemilian/triage/hemobox/data/f8-data-v2/frame_data_clean'
target_directory = '/Users/jamesemilian/triage/hemobox/data/f8-data-v2/2663250/images_all'

# Create target directory if it doesn't exist
os.makedirs(target_directory, exist_ok=True)

# Walk through the base directory
for root, dirs, files in os.walk(base_directory):
    # Check if the folder name is either 'extras' or 'raw_images'
    if os.path.basename(root) in ['extras', 'raw_images']:
        for file in files:
            # Only copy image files (you can add other extensions if needed)
            if file.endswith(('.jpg', '.png', '.jpeg', '.bmp', '.tiff')):
                source_file = os.path.join(root, file)
                target_file = os.path.join(target_directory, file)
                
                # Copy the file to the target directory
                shutil.copy(source_file, target_file)
                print(f"Copied: {file} from {root} to {target_directory}")

print("All images have been copied to 'images_all'.")


Let's get all the images without a blood mask now:

In [8]:
import os
import shutil

# Define folder paths
base_folder = 'data/f8-data-v2/2663250'
images_folder = os.path.join(base_folder, 'images_all')
masks_folder = os.path.join(base_folder, 'masks_rgb')
output_folder = os.path.join(base_folder, 'images_nohemo')

# Create output folder if it doesn't exist
os.makedirs(output_folder, exist_ok=True)

# Get list of image filenames without extension in masks folder (assuming .png files)
mask_files = {os.path.splitext(f)[0] for f in os.listdir(masks_folder) if f.endswith('.png')}

# Iterate through images folder and check for corresponding mask file
for image_file in os.listdir(images_folder):
    if image_file.endswith('.jpg'):
        image_name = os.path.splitext(image_file)[0]
        # If there is no corresponding mask file, copy the image to output folder
        if image_name not in mask_files:
            src_path = os.path.join(images_folder, image_file)
            dest_path = os.path.join(output_folder, image_file)
            shutil.copy(src_path, dest_path)
            print(f"Copied: {image_file}")

print("Script completed. Images without masks have been copied to 'images_nohemo'.")


Script completed. Images without masks have been copied to 'images_nohemo'.


In [10]:
import os
import shutil

# Define the base directory and target directory
base_directory = '/Users/jamesemilian/triage/hemobox/data/frame_data_clean'
target_directory = '/Users/jamesemilian/triage/hemobox/data/f8-data-v2/2663250/images_all'

# Create target directory if it doesn't exist
os.makedirs(target_directory, exist_ok=True)

# Walk through the base directory
for root, dirs, files in os.walk(base_directory):
    # Check if the folder name is either 'extras' or 'raw_images'
    if os.path.basename(root) in ['extras', 'raw_images']:
        for file in files:
            # Only copy image files (you can add other extensions if needed)
            if file.endswith(('.jpg', '.png', '.jpeg', '.bmp', '.tiff')):
                source_file = os.path.join(root, file)
                target_file = os.path.join(target_directory, file)
                
                # Copy the file to the target directory
                shutil.copy(source_file, target_file)
                print(f"Copied: {file} from {root} to {target_directory}")

print("All images have been copied to 'images_all'.")

All images have been copied to 'images_all'.


Note - above script does not work - just wait for Vinay's data. if i have the pipelines for GSAM and DINOv2 done - and data not here yet, then just run myself.

In [19]:
import os

# Directory containing the files
directory = "/Users/jamesemilian/triage/hemobox/data/2663250_v2/all_cleaned/images"

# Iterate through all files in the directory
for filename in os.listdir(directory):
    # Check if 'iphone' is in the filename
    if "iphone" in filename:
        try:
            # Split the filename into parts
            parts = filename.split("-")
            
            # Extract numeric parts (everything after 'regular' or similar words)
            numeric_parts = parts[1:]  # Skip the prefix (e.g., "iphone1_regular_view_...")
            
            # Combine the numeric parts and add the file extension
            new_filename = "".join(numeric_parts).replace(".png", "") + ".png"
            
            # Rename the file
            old_path = os.path.join(directory, filename)
            new_path = os.path.join(directory, new_filename)
            os.rename(old_path, new_path)
            print(f"Renamed: {filename} -> {new_filename}")
        except Exception as e:
            print(f"Error processing {filename}: {e}")


Renamed: iphone1_regular_view_arframe_image_compressed-1727622903-6757497.png -> 17276229036757497.png
Renamed: iphone1_regular_view_arframe_image_compressed-1727622896-239533185.png -> 1727622896239533185.png
Renamed: iphone1_regular_view_arframe_image_compressed-1727623184-976306438.png -> 1727623184976306438.png
Renamed: iphone3_regular_view_arframe_image_compressed-1727706848-487500190.png -> 1727706848487500190.png
Renamed: iphone4_regular_view_arframe_image_compressed-1727637604-698339939.png -> 1727637604698339939.png
Renamed: iphone4_rear_camera_view_image_compressed-1727707461-489413976.png -> 1727707461489413976.png
Renamed: iphone1_regular_view_arframe_image_compressed-1727623178-525881290.png -> 1727623178525881290.png
Renamed: iphone1_regular_view_arframe_image_compressed-1727622764-170843124.png -> 1727622764170843124.png
Renamed: iphone3_regular_view_arframe_image_compressed-1727638013-700551509.png -> 1727638013700551509.png
Renamed: iphone3_regular_view_arframe_image_c

In [14]:
import os

# Directory containing the files
directory = "/Users/jamesemilian/triage/hemobox/data/f8-data-v2/2663250_wcopy/masks_gray"

# Iterate through all files in the directory
for filename in os.listdir(directory):
    # Check if 'iphone' is in the filename
    if "iphone" in filename:
        try:
            # Split the filename into parts
            parts = filename.split("-")
            
            # Extract numeric parts (everything after 'regular' or similar words)
            numeric_parts = parts[1:]  # Skip the prefix (e.g., "iphone1_regular_view_...")
            
            # Combine the numeric parts and add the file extension
            new_filename = "".join(numeric_parts).replace(".png", "") + ".png"
            
            # Rename the file
            old_path = os.path.join(directory, filename)
            new_path = os.path.join(directory, new_filename)
            os.rename(old_path, new_path)
            print(f"Renamed: {filename} -> {new_filename}")
        except Exception as e:
            print(f"Error processing {filename}: {e}")


Renamed: iphone1_regular_view_arframe_image_compressed-1727622903-6757497.png -> 17276229036757497.png
Renamed: iphone1_regular_view_arframe_image_compressed-1727622896-239533185.png -> 1727622896239533185.png
Renamed: iphone1_regular_view_arframe_image_compressed-1727623184-976306438.png -> 1727623184976306438.png
Renamed: iphone3_regular_view_arframe_image_compressed-1727706848-487500190.png -> 1727706848487500190.png
Renamed: iphone4_regular_view_arframe_image_compressed-1727637604-698339939.png -> 1727637604698339939.png
Renamed: iphone4_rear_camera_view_image_compressed-1727707461-489413976.png -> 1727707461489413976.png
Renamed: iphone1_regular_view_arframe_image_compressed-1727623178-525881290.png -> 1727623178525881290.png
Renamed: iphone1_regular_view_arframe_image_compressed-1727622764-170843124.png -> 1727622764170843124.png
Renamed: iphone3_regular_view_arframe_image_compressed-1727638013-700551509.png -> 1727638013700551509.png
Renamed: iphone3_regular_view_arframe_image_c

In [15]:
import os
from datetime import datetime

# Directory containing the files
directory = "/Users/jamesemilian/triage/hemobox/data/f8-data-v2/2663250_wcopy/images"

# Iterate through all files in the directory
for filename in os.listdir(directory):
    # Check if the file matches the pattern "image_YYYYMMDD_HHMMSS.png"
    if filename.startswith("image_") and filename.endswith(".png"):
        try:
            # Extract the datetime part from the filename
            parts = filename.split("_")
            date_part = parts[1]  # YYYYMMDD
            time_part = parts[2].replace(".png", "")  # HHMMSS

            # Combine and parse into a datetime object
            dt = datetime.strptime(date_part + time_part, "%Y%m%d%H%M%S")
            
            # Convert to Unix timestamp in nanoseconds
            unix_ns = int(dt.timestamp() * 1e9)  # Convert to nanoseconds
            
            # Create the new filename
            new_filename = f"{unix_ns}.png"
            
            # Rename the file
            old_path = os.path.join(directory, filename)
            new_path = os.path.join(directory, new_filename)
            os.rename(old_path, new_path)
            print(f"Renamed: {filename} -> {new_filename}")
        except Exception as e:
            print(f"Error processing {filename}: {e}")


Renamed: image_20231129_141212.png -> 1701285132000000000.png
Renamed: image_20231129_141216.png -> 1701285136000000000.png
Renamed: image_20231129_141840.png -> 1701285520000000000.png
Renamed: image_20231129_141539.png -> 1701285339000000000.png
Renamed: image_20231129_141857.png -> 1701285537000000000.png
Renamed: image_20231129_140601.png -> 1701284761000000000.png
Renamed: image_20231129_141910.png -> 1701285550000000000.png
Renamed: image_20231129_141051.png -> 1701285051000000000.png
Renamed: image_20231129_141849.png -> 1701285529000000000.png
Renamed: image_20231129_141232.png -> 1701285152000000000.png
Renamed: image_20231129_135809.png -> 1701284289000000000.png
Renamed: image_20231129_140517.png -> 1701284717000000000.png
Renamed: image_20231129_141224.png -> 1701285144000000000.png


In [18]:
import os
from datetime import datetime

# Directory containing the files
# directory = "/Users/jamesemilian/triage/hemobox/data/f8-data-v2/2663250_wcopy/masks_rgb"
directory = "/Users/jamesemilian/triage/hemobox/data/f8-data-v2/2663250_wcopy/masks_gray"
# Iterate through all files in the directory
for filename in os.listdir(directory):
    # Check if the file matches the pattern "image_YYYYMMDD_HHMMSS.png"
    if filename.startswith("image_") and filename.endswith(".png"):
        try:
            # Extract the datetime part from the filename
            parts = filename.split("_")
            date_part = parts[1]  # YYYYMMDD
            time_part = parts[2].replace(".png", "")  # HHMMSS

            # Combine and parse into a datetime object
            dt = datetime.strptime(date_part + time_part, "%Y%m%d%H%M%S")
            
            # Convert to Unix timestamp in nanoseconds
            unix_ns = int(dt.timestamp() * 1e9)  # Convert to nanoseconds
            
            # Create the new filename
            new_filename = f"{unix_ns}.png"
            
            # Rename the file
            old_path = os.path.join(directory, filename)
            new_path = os.path.join(directory, new_filename)
            os.rename(old_path, new_path)
            print(f"Renamed: {filename} -> {new_filename}")
        except Exception as e:
            print(f"Error processing {filename}: {e}")


Renamed: image_20231129_141212.png -> 1701285132000000000.png
Renamed: image_20231129_141216.png -> 1701285136000000000.png
Renamed: image_20231129_141840.png -> 1701285520000000000.png
Renamed: image_20231129_141539.png -> 1701285339000000000.png
Renamed: image_20231129_141857.png -> 1701285537000000000.png
Renamed: image_20231129_140601.png -> 1701284761000000000.png
Renamed: image_20231129_141910.png -> 1701285550000000000.png
Renamed: image_20231129_141051.png -> 1701285051000000000.png
Renamed: image_20231129_141849.png -> 1701285529000000000.png
Renamed: image_20231129_141232.png -> 1701285152000000000.png
Renamed: image_20231129_135809.png -> 1701284289000000000.png
Renamed: image_20231129_140517.png -> 1701284717000000000.png
Renamed: image_20231129_141224.png -> 1701285144000000000.png


So this is the pipeline for cleaning data - can pass through once I have 'empty blood masks' from Vinay too.